pr:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: which python
  displayName: check python bin

- script: |
    conda install -c anaconda hdf5 
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pip install -e .
  displayName: 'install test deps'

- script: |
    pytest ./modin/pandas/test/test_api.py
  displayName: 'pytest test-run'
